### ISSUE TITLE
Enumeration of driver commits only includes changes to entrypoint

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/compiler#14]
[Currently](https://github.com/PlaceOS/compiler/blob/db6037aef41ee8ce02d4c05322fdbdf6406c64dd/src/placeos-compiler/helper.cr#L65) when enumerating driver-level commits, the results filter to those that include changes to the driver entrypoint only. If a driver is split across multiple files (`foo.cr`, `foo/client.cr`, `foo/errors.cr`, or for a [concrete example](https://github.com/PlaceOS/drivers/tree/lenel/drivers/lenel)) this misses relevant commits.

User visible behaviour of this is a repository may be pulled in backoffice, the repository will show the HEAD commit, but it is not possible to point a driver to it and build it.

A workaround is to make a minor / sacrificial change to the driver entrypoint, at which point it will be possible to bump the commit reference.

A solution is a little more challenging. Walking the `require` tree would need to happen for each commit so results in a potential complexity explosion on larger repos, or those with a long history.

This is likely best suited to a larger discussion on the best way to handle drivers versioning, releases, their deps etc. Options exist to move this to a more formal release setup (some form of additional metadata either in the entrypoint, a driver-level `shard.yml` or something custom) and provide these as the points to pin to from within deploys.

**Comment by caspiano** [comment]
A driver should have its own directory, with its own `shard.yml`.
I think it makes sense as drivers are essentially independent applications.
With this constraint, checking for driver-level commits should be much easier.

**Comment by kimburgess** [comment]
Yep, I'd agree with that approach. It's familiar tooling, provides all the metadata needed and can also use the shards cache for external dependencies that are shared between drivers.

The only edge case I can think of with the one-driver-per-folder approach is situations where drivers use a shared component that it's is not standalone shard worthy. As an example: a module that provides the high level manufacturer protocol, which is used by a number of different drivers for devices from that manufacturer.

One approach:
```
vendor_name/
├─ lib/
│  ├─ protocol_name.cr
├─ device_a/
│  ├─ shard.yml
│  ├─ device_a.cr
│  ├─ device_a_spec.cr
├─ device_b/
│  ├─ shard.yml
│  ├─ device_b.cr
│  ├─ device_b_spec.cr
...
```
`../lib` or even `lib` at each point in the tree can be added to the compiler path. This would definitely work for the compiler, but may break dev tooling as any static analysis won't be able to locate those shared deps.

**Comment by caspiano** [comment]
`build` has the `digest_cli` program that traverses the requires of a program and tells you all files that are touched.

Adding an argument `--files` that just spits out the require tree (as a list) could be very beneficial in solving this exact problem, as that output can be the `rev-list` arg to `git log`

**Comment by caspiano** [comment]
This essentially means here we should extend `Git.commits` to accept an array of files. We'll also throw the `shard.lock` into this list of files.
