### ISSUE TITLE
Independent Driver compilation

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/compiler#6]
General cleanup and boost of reproducibility in `Driver` compilation.

- Extract `crystal` version from the driver/s `shard.yml` and compile with an appropriate compiler version
- Use driver's local shards or fallback to the driver's repository shards

**Comment by kimburgess** [comment]
Adding some notes here (more for self-reference - but open to comment).

One possible implementation here is running driver builds in an external container that shares a volume with core nodes (in a distributed deploy this will likely mean these will need to run as sidecars). Core will need to flag a driver as requiring rebuild (paths for this are via shared fs or inter-service request). These build containers can then have different crystal compiler versions available and update independently of core.

_If_ this happens it may make sense to shift all repository management to this container too. This has the advantage of isolating anything that's pulling + building things from the outside world from where they are run.

Possible tools for crystal version management
 - [Nix](https://nixos.org/) (:heart:)
 - [crenv](https://github.com/crenv/crenv/)
 - [asdf](https://github.com/asdf-community/asdf-crystal)

**Comment by stakach** [comment]
Yeah makes sense to launch a container in the container to perform compilation.
Probably the simplest way to go about it

**Comment by caspiano** [comment]
> Yeah makes sense to launch a container in the container to perform compilation.
> Probably the simplest way to go about it

Are you suggesting docker in docker?

**Comment by stakach** [comment]
yeah, for the sole purpose of compilation with a particular version of crystal
launches the container with an `exec` command and maps in the `repository` and `bin` folders.
the script or executable in the image downloads the appropriate version of crystal and compiles

I assume we do the shards install externally to save time.

**Comment by kimburgess** [comment]
I'm not sure if docker-in-docker is the best way to go. At least historically that would require some security compromises that while fine for some environments, make it incompatible with this use case.

The notes above were more in reference to having a build container spinning on the outer host / pod which shares a volume with `core`, or a standalone service that accepts a repo, commit and path then returns a binary. This container can then either come with a static set of compilers baked in (and have it's image updated separately from core), or be capable of pulling fresh compilers as required as though it was just another dep).

I haven't had the mental capacity to give this too much deep though yet, but will try to flesh this out a little more this week.

**Comment by caspiano** [comment]
Duplicate of PlaceOS/build#8
